import type { NextPage } from 'next'
import Head from 'next/head'

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 style={{ textAlign: 'center' }}>About Covid Cert</h2>
      </main>
    </div>
  )
}

export default About
