import type { NextPage } from 'next'
import Head from 'next/head'

const PrivacyPolicy: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 style={{ textAlign: 'center' }}>Privacy Policy</h2>
        <p>bla bla bla bla</p>
      </main>
    </div>
  )
}

export default PrivacyPolicy
