import type { NextPage } from 'next'
import Head from 'next/head'

const Privacity: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Privacity Police</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 style={{ textAlign: 'center' }}>Privacity Police</h2>
        <p>bla bla bla bla</p>
      </main>
    </div>
  )
}

export default Privacity
