/* eslint-disable @next/next/no-html-link-for-pages */
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

const Preview: NextPage = () => {
  const router = useRouter()
  const url = sessionStorage.getItem('covid-scan-url') || ''

  return (
    <div>
      <Head>
        <title>Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ margin: '20px 20%' }}>
        PREVIEW
        

        <a href={ `/api/pass?code=${url}` }>DOWNLOAD WALLET PASS</a>
      </main>
    </div>
  )
}

export default Preview
